# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'rspec', :version => 2 do
  watch(%r{^domain_model/spec/.+_spec\.rb$})
  watch(%r{^domain_model/lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
end

